In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

In [4]:
df.sample(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
4814,4815,15615896,Chienezie,621,Spain,Male,39,8,0.0,2,1,0,36122.96,0
5322,5323,15699830,Doherty,721,France,Female,40,7,0.0,2,1,1,122580.48,0
4927,4928,15803456,Yen,641,France,Female,40,9,0.0,1,0,0,151648.66,1
1087,1088,15696098,Palermo,498,France,Female,31,10,0.0,2,1,0,13892.57,0
2198,2199,15573876,Chia,473,Spain,Male,48,8,0.0,2,1,0,71139.80,0

In [5]:
df.drop(columns= ['RowNumber','CustomerId','Surname'] , inplace=True)

In [6]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [8]:
df['Geography'].nunique()

3

In [9]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [10]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [15]:
df = pd.get_dummies(df, columns=['Geography' , 'Gender'] , dtype="int64" , drop_first=True)

In [16]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [20]:
X = df.drop(columns=['Exited'])

In [21]:
X.sample(5)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
7986,667,45,3,0.00,2,0,0,163655.01,0,1,1
53,655,41,8,125561.97,1,0,0,164040.94,1,0,1
8593,610,36,7,115462.02,1,0,1,42581.04,1,0,1
4862,645,55,1,133676.65,1,0,1,17095.49,0,1,0
9113,521,29,2,87212.80,1,1,1,994.86,1,0,0

In [24]:
y = df['Exited'].values

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2 , random_state=1)

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
scaler = StandardScaler()

In [29]:
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [30]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [32]:
X_train_trf.shape

(8000, 11)

In [31]:
model = Sequential()

In [49]:
model.add(Dense(5, activation='sigmoid' , input_dim = 11))
model.add(Dense(3, activation='sigmoid' ))
model.add(Dense(1, activation='sigmoid' ))

/home/subhamoy/miniforge3/envs/tf_gpu/lib/python3.12/site-packages/keras/src/layers/core/dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [50]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 5)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            18 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 115 (464.00 B)

 Trainable params: 59 (236.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 56 (228.00 B)

In [51]:
model.compile(optimizer='Adam' , loss = 'binary_crossentropy' )

In [52]:
model.fit(X_train_trf , y_train , epochs=100, batch_size=50)

Epoch 1/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.5050
Epoch 2/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4999
Epoch 3/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4974
Epoch 4/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4941
Epoch 5/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4899
Epoch 6/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4846
Epoch 7/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4785
Epoch 8/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4715
Epoch 9/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4643
Epoch 10/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4570
Epoch 11/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4504
Epoch 12/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4447
Epoch 13/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4399
Epoch 14/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4360
Epoch 15/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4329
Epoch 16/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4304
Epoch 17/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4284
Epoch 18/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4266
Epoch 19/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4252
Epoch 20/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4240
Epoch 21/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4230
Epoch 22/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4221
Epoch 23/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.4212
Epoch 24/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4205
Epoch 25/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4199
Epoch 26/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4193
Epoch 27/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4188
Epoch 28/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4183
Epoch 29/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4179
Epoch 30/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4173
Epoch 31/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4171
Epoch 32/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4166
Epoch 33/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4163
Epoch 34/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4160
Epoch 35/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4155
Epoch 36/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4153
Epoch 37/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4151
Epoch 38/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4149
Epoch 39/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4145
Epoch 40/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4143
Epoch 41/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4139
Epoch 42/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4138
Epoch 43/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4136
Epoch 44/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4132
Epoch 45/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4130
Epoch 46/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4128
Epoch 47/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4126
Epoch 48/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4122
Epoch 49/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4121
Epoch 50/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4120
Epoch 51/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4117
Epoch 52/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4114
Epoch 53/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4111
Epoch 54/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4110
Epoch 55/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4108
Epoch 56/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4105
Epoch 57/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4104
Epoch 58/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4102
Epoch 59/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4100
Epoch 60/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4098
Epoch 61/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4096
Epoch 62/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4094
Epoch 63/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4093
Epoch 64/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4091
Epoch 65/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4089
Epoch 66/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4088
Epoch 67/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4085
Epoch 68/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4084
Epoch 69/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4082
Epoch 70/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4083
Epoch 71/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4081
Epoch 72/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4077
Epoch 73/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4077
Epoch 74/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4076
Epoch 75/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4075
Epoch 76/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4075
Epoch 77/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4074
Epoch 78/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4072
Epoch 79/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4071
Epoch 80/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4070
Epoch 81/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4070
Epoch 82/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4068
Epoch 83/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4068
Epoch 84/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4066
Epoch 85/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4066
Epoch 86/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4065
Epoch 87/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4063
Epoch 88/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4064
Epoch 89/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4063
Epoch 90/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4061
Epoch 91/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4061
Epoch 92/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4062
Epoch 93/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4060
Epoch 94/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4058
Epoch 95/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4058
Epoch 96/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4058
Epoch 97/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4057
Epoch 98/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4057
Epoch 99/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4055
Epoch 100/100
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4056

In [53]:
y_pred = model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [54]:
y_pred = (y_pred > 0.5)

In [55]:
y_pred = (y_pred > 0.5).astype(int)

In [44]:
(y_pred > 0.5).astype(int)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], shape=(2000, 1))

In [45]:
y_test

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [56]:
y_pred.reshape(y_test.shape)

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.834

In [58]:
X_test.shape

(2000, 11)

In [59]:
X_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
9953,550,47,2,0.00,2,1,1,97057.28,0,0,1
3850,680,34,3,143292.95,1,1,0,66526.01,0,0,1
4962,531,42,2,0.00,2,0,1,90537.47,0,0,0
3886,710,34,8,147833.30,2,0,1,1561.58,1,0,1
5437,543,30,6,73481.05,1,1,1,176692.65,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
3919,763,39,7,0.00,2,1,0,19458.75,0,1,0
162,800,49,7,108007.36,1,0,0,47125.11,0,0,0
7903,567,34,10,0.00,2,0,1,161571.79,0,1,1
2242,621,30,2,101014.08,2,1,1,165257.31,1,0,0
2745,655,52,9,144696.75,1,1,1,49025.79,1,0,1